name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: zip -r deploy.zip . -x '*.git*'
      - uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
          application_name: eb-node-express
          environment_name: eb-node-express
          version_label: ${{ github.run_number }}
          region: us-east-1
          deployment_package: deploy.zip
